name: Generate demo-script

on:
  workflow_run:
    workflows:
      - "Basic build and test"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.workflow_run.head_branch || github.event.ref || github.ref }}"
  cancel-in-progress: false

jobs:
  generate-demo-script-resources:
    if: ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'workflow_run') && ((github.event.workflow_run.event == 'push') || (github.event.workflow_run.event == 'workflow_dispatch')) && (github.event.workflow_run.conclusion == 'success')))
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - name: Calculate REF (workflow_run event)
        if: github.event_name == 'workflow_run'
        run: echo "REF=${{ github.event.workflow_run.head_commit.id }}" >> $GITHUB_ENV

      - name: Calculate REF (workflow_dispatch event)
        if: github.event_name == 'workflow_dispatch'
        run: echo "REF=${{ github.sha }}" >> $GITHUB_ENV

      - uses: actions/checkout@v5

      - name: Install Asciidoctor Reducer
        run: sudo gem install asciidoctor-reducer

      - name: Install Asciidoctor PDF
        run: sudo gem install asciidoctor-pdf

      - name: Reduce README
        working-directory: demo
        # to preserve preprocessor conditionals, add the --preserve-conditionals option
        run: asciidoctor-reducer -o demo-script.adoc demo-script-source.adoc

      - name: Generate PDF
        working-directory: demo
        run: asciidoctor-pdf --theme demo-pdf -a pdf-themesdir=. -o demo-script.pdf demo-script-source.adoc

      - name: Commit generated documents via PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            demo/demo-script.adoc
            demo/demo-script.pdf
          commit-message: "Generate demo script (from ${{ github.workflow }} run # ${{ github.run_number }})"
          branch: generate-demo-script-resources
          delete-branch: true
          title: "Generate demo script (from ${{ github.workflow }} run # ${{ github.run_number }})"
          body: "Generated demo script changes from [${{ github.workflow }} run # ${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}), which was triggered by commit ${{ env.REF }}."

      - name: Merge PR
        if: (steps.create-pr.outputs.pull-request-operation == 'created') && (steps.create-pr.outputs.pull-request-number)
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        run: gh pr merge --squash --admin ${{ steps.create-pr.outputs.pull-request-number }}
