name: Basic build and test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/generate-demo-script.yml'
      - 'demo/demo-script.adoc'
      - 'demo/demo-script.pdf'
      - 'demo/intellij-live-templates/**'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/generate-demo-script.yml'
      - 'demo/demo-script.adoc'
      - 'demo/demo-script.pdf'
      - 'demo/intellij-live-templates/**'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build-test-jvm
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0

  jvm-container-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build-test-jvm-container
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dquarkus.container-image.build=true

  native-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'mandrel'
          cache: 'maven'
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'

      - name: build-test-native
        run: ./mvnw -B clean verify -Pnative -Dquarkus.http.host=0.0.0.0 -Dmaven.compiler.release=21

  native-container-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build-test-native-container
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.native.container-build=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=21
